name: Jason Poon
favicon: null
layout_spectrum: 0.40558974351733923
typography_spectrum: 0.7590152095071971
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9299998069182038
  lightness: 0.9767575736623257
  saturation: 0.9791230410337448
  rhythmicContrast: 0.6349524268880486
purpose: []
